// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaufITJhEiUWntUZLwxfFQwlN9bixHhWc',
    appId: '1:6011918544:web:c62108080b6f79273526d5',
    messagingSenderId: '6011918544',
    projectId: 'descartable-server',
    authDomain: 'descartable-server.firebaseapp.com',
    databaseURL: 'https://descartable-server-default-rtdb.firebaseio.com',
    storageBucket: 'descartable-server.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdYwbdlD-D0WriU2I2HRFgTmIns_DO5Ug',
    appId: '1:6011918544:android:baff249060691b793526d5',
    messagingSenderId: '6011918544',
    projectId: 'descartable-server',
    databaseURL: 'https://descartable-server-default-rtdb.firebaseio.com',
    storageBucket: 'descartable-server.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOQ7wAnZ_DE6wyB2A4IvYwkbZThXWtixQ',
    appId: '1:6011918544:ios:f97b010484d18c223526d5',
    messagingSenderId: '6011918544',
    projectId: 'descartable-server',
    databaseURL: 'https://descartable-server-default-rtdb.firebaseio.com',
    storageBucket: 'descartable-server.appspot.com',
    androidClientId: '6011918544-cdkj5r8f7s2tjgusja77ue9vhahbhe7q.apps.googleusercontent.com',
    iosClientId: '6011918544-2kt1usd9lqk45ck1pgvksc22mf7o71mn.apps.googleusercontent.com',
    iosBundleId: 'com.souvikbiswas.flutterfireExamples',
  );
}
